language: node_js
cache:
  npm: false
script:
- npm run lint
- npm run test
- npm run coverage
before_install:
- openssl aes-256-cbc -K $encrypted_ba0d7aaa5a42_key -iv $encrypted_ba0d7aaa5a42_iv
  -in travis_github_key.enc -out travis_github_key -d
- chmod 600 travis_github_key
- eval "$(ssh-agent -s)"
- ssh-add travis_github_key
