language: node_js
cache:
  npm: false
script:
- npm run lint
- npm run test
- npm run coverage
before_install:
- openssl aes-256-cbc -K $encrypted_c589161bbc05_key -iv $encrypted_c589161bbc05_iv
  -in .env.test.enc -out .env.test -d
- openssl aes-256-cbc -K $encrypted_d47601e7a41c_key -iv $encrypted_d47601e7a41c_iv
  -in didi-next-00-firebase-adminsdk-iev7z-d7cc5b46ef.json.enc -out ./services/didi-next-00-firebase-adminsdk-iev7z-d7cc5b46ef.json
  -d
- openssl aes-256-cbc -K $encrypted_ba0d7aaa5a42_key -iv $encrypted_ba0d7aaa5a42_iv
  -in travis_github_key.enc -out /home/travis/.ssh/id_rsa -d
- chmod 600 /home/travis/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add /home/travis/.ssh/id_rsa
- git config --global user.email "travis.ci@didi.org.ar"
- git config --global user.name "didi-ssi-travis-bot"
