version: "3"
services:
  didi-server:
    image: aidi00.azurecr.io/didi-server:dev
    environment:
      - VERSION=${VERSION}
      - ENABLE_INSECURE_ENDPOINTS=${DIDI_ENABLE_INSECURE_ENDPOINTS}
      - DEBUGG_MODE=${DIDI_SERVER_DEBUGG}
      - MONGO_DIR=${DIDI_SERVER_MONGO_DIR}
      - MONGO_PORT=${DIDI_SERVER_MONGO_PORT}
      - MONGO_USERNAME=${DIDI_SERVER_MONGO_USER}
      - MONGO_PASSWORD=${DIDI_SERVER_MONGO_PASSWORD}
      - MONGO_DB=${DIDI_SERVER_MONGO_DB}
      - ADDRESS=${DIDI_SERVER_ADDRESS}
      - PORT=${DIDI_SERVER_PORT}
      - SERVER_DID=${DIDI_SERVER_DID}
      - SERVER_PRIVATE_KEY=${DIDI_SERVER_PRIVATE_KEY}
      - ISSUER_SERVER_DID=${ISSUER_SERVER_DID}
      - ISSUER_SERVER_NAME=${ISSUER_SERVER_NAME}
      - MOURO_URL=${DIDI_SERVER_MOURO_URL}
      - MAILGUN_API_KEY=${DIDI_SERVER_MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${DIDI_SERVER_MAILGUN_DOMAIN}
      - TWILIO_SID=${DIDI_SERVER_TWILIO_SID}
      - TWILIO_TOKEN=${DIDI_SERVER_TWILIO_TOKEN}
      - TWILIO_PHONE_NUMBER=${DIDI_SERVER_TWILIO_PHONE_NUMBER}
      - SERVER_IP=${DIDI_SERVER_IP}
      - RENAPER_SCORE_TRESHOULD=${DIDI_SERVER_RENAPER_SCORE_TRESHOULD}
      - RENAPER_API_KEY=${DIDI_SERVER_RENAPER_API_KEY}
      - RENAPER_API=${DIDI_SERVER_RENAPER_API}
      - RENAPER_URL=${DIDI_SERVER_RENAPER_URL}
      - FINGER_PRINT_DATA=${DIDI_SERVER_FINGER_PRINT_DATA}
      - NO_EMAILS=${DIDI_SERVER_NO_EMAILS}
      - NO_SMS=${DIDI_SERVER_NO_SMS}
      - BLOCKCHAIN_URL_MAIN=${BLOCKCHAIN_URL_MAIN}
      - BLOCKCHAIN_URL_RSK=${BLOCKCHAIN_URL_RSK}
      - BLOCKCHAIN_URL_LAC=${BLOCKCHAIN_URL_LAC}
      - BLOCKCHAIN_URL_BFA=${BLOCKCHAIN_URL_BFA}
      - BLOCKCHAIN_CONTRACT_MAIN=${BLOCKCHAIN_CONTRACT_MAIN}
      - BLOCKCHAIN_CONTRACT_RSK=${BLOCKCHAIN_CONTRACT_RSK}
      - BLOCKCHAIN_CONTRACT_LAC=${BLOCKCHAIN_CONTRACT_LAC}
      - BLOCKCHAIN_CONTRACT_BFA=${BLOCKCHAIN_CONTRACT_BFA}
      - BLOCK_CHAIN_DELEGATE_DURATION=${BLOCK_CHAIN_DELEGATE_DURATION}
      - RSA_PRIVATE_KEY=${DIDI_SERVER_RSA_PRIVATE_KEY}
      - HASH_SALT=${DIDI_SERVER_HASH_SALT}
      - FIREBASE_URL=${DIDI_SERVER_FIREBASE_URL}
      - FIREBASE_PRIV_KEY_PATH=${FIREBASE_PRIV_KEY_PATH}
      - APP_INSIGTHS_IKEY=${APP_INSIGTHS_IKEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - NAME=${DIDI_SERVER_NAME}
      - DISABLE_TELEMETRY_CLIENT=${DISABLE_TELEMETRY_CLIENT} # ???
      - SEMILLAS_URL=${DIDI_SERVER_SEMILLAS_URL}
      - SEMILLAS_USERNAME=${DIDI_SERVER_SEMILLAS_USERNAME}
      - SEMILLAS_PASSWORD=${DIDI_SERVER_SEMILLAS_PASSWORD}
    depends_on:
      - db
    ports:
      - "8089:${DIDI_SERVER_PORT}"
    volumes:
      - "./var/log/didi:/var/log/didi"
      - "./configs:/configs"
  mouro-gql:
    image: aidi00.azurecr.io/didi-mouro:dev
    environment:
      - DIDI_SERVER_DID=${DIDI_SERVER_DID}
      - MOURO_PORT=${MOURO_PORT}
      - SWARM_URL=${SWARM_URL}
      - SWARM_PORT=${SWARM_PORT}
      - SQLITE_FILE=${SQLITE_FILE}
      - BLOCK_CHAIN_URL=${BLOCK_CHAIN_URL}
      - BLOCK_CHAIN_CONTRACT=${BLOCK_CHAIN_CONTRACT}
      - APP_INSIGTHS_IKEY=${APP_INSIGTHS_IKEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - NAME=${MOURO_NAME}
      - DISABLE_TELEMETRY_CLIENT=${DISABLE_TELEMETRY_CLIENT}
      - BLOCKCHAIN_URL_MAIN=${BLOCKCHAIN_URL_MAIN}
      - BLOCKCHAIN_URL_RSK=${BLOCKCHAIN_URL_RSK}
      - BLOCKCHAIN_URL_LAC=${BLOCKCHAIN_URL_LAC}
      - BLOCKCHAIN_URL_BFA=${BLOCKCHAIN_URL_BFA}
      - BLOCKCHAIN_CONTRACT_MAIN=${BLOCKCHAIN_CONTRACT_MAIN}
      - BLOCKCHAIN_CONTRACT_RSK=${BLOCKCHAIN_CONTRACT_RSK}
      - BLOCKCHAIN_CONTRACT_LAC=${BLOCKCHAIN_CONTRACT_LAC}
      - BLOCKCHAIN_CONTRACT_BFA=${BLOCKCHAIN_CONTRACT_BFA}
    ports: 
      - "127.0.0.1:3000:${MOURO_PORT}"
    volumes:
      - "./didi/mouro-data:/database"
  db:
    image: mongo:4.4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ADMIN_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ADMIN_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${ADMIN_DB}
      - DIDI_SERVER_MONGO_DB=${DIDI_SERVER_MONGO_DB}
      - DIDI_SERVER_MONGO_USER=${DIDI_SERVER_MONGO_USER}
      - DIDI_SERVER_MONGO_PASSWORD=${DIDI_SERVER_MONGO_PASSWORD}
      - ISSUER_MONGO_DB=${ISSUER_MONGO_DB}
      - ISSUER_MONGO_USERNAME=${ISSUER_MONGO_USERNAME}
      - ISSUER_MONGO_PASSWORD=${ISSUER_MONGO_PASSWORD}
    volumes:
      - "./db-data:/data/db"
      - "./configs:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    ports:
      - 127.0.0.1:27017:27017
